from tkinter import *
root = Tk()
def inpcmd(number):
    x = e1.get()
    e1.delete(0, END)
    e1.insert(0, str(x) + str(number))
    
def clrcmd():
    e1.delete(0, END
    )   

e1 = Entry(root, width=34)
e1.grid(row=0, column=0, columnspan=20)
l1 = Label(root)
l1.grid(row=1, column=0)
l2 = Label(root)
l2.grid(row=2, column=0)
l3 = Label(root)
l3.grid(row=3, column=0)
l4 = Label(root)
l4.grid(row=4, column=0)
l5 = Label(root)
l5.grid(row=5, column=0)
l6 = Label(root)
l6.grid(row=6, column=0)
l7 = Label(root)
l7.grid(row=7, column=0)
l8 = Label(root)
l8.grid(row=8, column=0)
l9 = Label(root)
l9.grid(row=9, column=0)
l10 = Label(root)
l10.grid(row=10, column=0)

b1 = Button(root, text="A", command=lambda:inpcmd("A"), bg="darkorange")
b1.grid(row=11, column=0,)
b2 = Button(root, text="B", command=lambda:inpcmd("B"), bg="darkorange")
b2.grid(row=11, column=1)
b3 = Button(root, text="C", command=lambda:inpcmd("C"), bg="darkorange")
b3.grid(row=11, column=2)
b4 = Button(root, text="D", command=lambda:inpcmd("D"), bg="darkorange")
b4.grid(row=11, column=3,)
b5 = Button(root, text="E", command=lambda:inpcmd("E"), bg="darkorange")
b5.grid(row=11, column=4)
b6 = Button(root, text="F", command=lambda:inpcmd("F"), bg="darkorange")
b6.grid(row=11, column=5)
b7 = Button(root, text="G", command=lambda:inpcmd("G"), bg="darkorange")
b7.grid(row=12, column=0,)
b8 = Button(root, text="H", command=lambda:inpcmd("H"), bg="darkorange")
b8.grid(row=12, column=1)
b9 = Button(root, text="I", command=lambda:inpcmd("I"), bg="darkorange")
b9.grid(row=12, column=2)
b10 = Button(root, text="J", command=lambda:inpcmd("J"), bg="darkorange")
b10.grid(row=12, column=3,)
b11 = Button(root, text="K", command=lambda:inpcmd("K"), bg="darkorange")
b11.grid(row=12, column=4)
b12 = Button(root, text="L", command=lambda:inpcmd("L"), bg="darkorange")
b12.grid(row=12, column=5)

b13 = Button(root, text="M", command=lambda:inpcmd("M"), bg="darkorange")
b13.grid(row=13, column=0,)
b14 = Button(root, text="N", command=lambda:inpcmd("N"), bg="darkorange")
b14.grid(row=13, column=1)
b15 = Button(root, text="O", command=lambda:inpcmd("O"), bg="darkorange")
b15.grid(row=13, column=2)
b16 = Button(root, text="P", command=lambda:inpcmd("P"), bg="darkorange")
b16.grid(row=13, column=3,)
b17 = Button(root, text="Q", command=lambda:inpcmd("Q"), bg="darkorange")
b17.grid(row=13, column=4)
b18 = Button(root, text="R", command=lambda:inpcmd("R"), bg="darkorange")
b18.grid(row=13, column=5)

b19 = Button(root, text="S", command=lambda:inpcmd("S"), bg="darkorange")
b19.grid(row=14, column=0,)
b20 = Button(root, text="T", command=lambda:inpcmd("T"), bg="darkorange")
b20.grid(row=14, column=1)
b21 = Button(root, text="U", command=lambda:inpcmd("U"), bg="darkorange")
b21.grid(row=14, column=2)
b22 = Button(root, text="V", command=lambda:inpcmd("V"), bg="darkorange")
b22.grid(row=14, column=3,)
b23 = Button(root, text="W", command=lambda:inpcmd("W"), bg="darkorange")
b23.grid(row=14, column=4)
b24 = Button(root, text="X", command=lambda:inpcmd("X"), bg="darkorange")
b24.grid(row=14, column=5)

b25 = Button(root, text="Y", command=lambda:inpcmd("Y"), bg="darkorange")
b25.grid(row=15, column=0,)
b26 = Button(root, text="Z", command=lambda:inpcmd("Z"), bg="darkorange")
b26.grid(row=15, column=1)
b27 = Button(root, text="|_|", command=lambda:inpcmd(" "), bg="darkorange")
b27.grid(row=15, column=2)
b28 = Button(root, text="×", command=clrcmd, bg="darkorange")
b28.grid(row=15, column=3)

root.mainloop()
